In [8]:
import torch
import numpy as np

In [9]:
t = np.array([0, 1, 2, 3, 4, 5, 6])
print(t)

[0 1 2 3 4 5 6]


In [10]:
print('Rank of t :', t.ndim)
print('shape of t:', t.shape)

Rank of t : 1
shape of t: (7,)


In [11]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1])
print('t[2:] t[3:] = ', t[:2], t[3:])

t[0] t[1] t[-1] =  0 1 6
t[2:5] t[4:-1] =  [2 3 4] [4 5]
t[2:] t[3:] =  [0 1] [3 4 5 6]


In [12]:
t = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(t)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
print('Rank of t:', t.ndim)
print('Shape of t:', t.shape)

Rank of t: 2
Shape of t: (4, 3)
